version: "2.2"

services:
#  fleet_token:
#    depends_on:
#      kibana:
#        condition: service_healthy
#    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
#    volumes:
#      - ./secrets/certs:/usr/share/elasticsearch/config/certs
#      - ./setup:/setup
#      - ./.env:/setup/.env:rw
#    user: "0"
#    environment:
#      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
#    command: bash /setup/fleet_token.sh
#    healthcheck:
#      test: exit 0
#      interval: 1s
#      timeout: 5s
#      retries: 120

  fleet_server:
    image: docker.elastic.co/beats/elastic-agent:8.0.0
#    depends_on:
#      fleet_token:
#        condition: service_started
#    env_file:
#      - ./setup/fleet.token
    environment:
      - "FLEET_SERVER_ENABLE=1"
      - "FLEET_SERVER_INSECURE_HTTP=0"
      - "FLEET_INSECURE=1"
      - "FLEET_ENROLL=1"
      - "FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDU2NTIxNTE2NTI6SWx6eFhBeXpRQktYenpheTJYSzduQQ"
      - "FLEET_SERVER_CERT=/usr/share/elastic-agent/cert.crt"
      - "FLEET_SERVER_CERT_KEY=/usr/share/elastic-agent/cert.key"
      - "FLEET_URL=https://192.168.56.101:8220"
      - "FLEET_SERVER_ELASTICSEARCH_HOST=https://192.168.56.101:9200"
      - "FLEET_SERVER_ELASTICSEARCH_CA=/usr/share/elastic-agent/ca.pem"
      - "KIBANA_FLEET_CA=/usr/share/elastic-agent/ca.pem"
      - "FLEET_CA=/usr/share/elastic-agent/ca.pem"
      - "ELASTICSEARCH_CA=/usr/share/elastic-agent/ca.pem"
      - "KIBANA_CA=/usr/share/elastic-agent/ca.pem"
    ports:
      - "8220:8220"
    healthcheck:
      test: "curl -f http://127.0.0.1:8220/api/status | grep HEALTHY 2>&1 >/dev/null"
      retries: 12
      interval: 5s
    volumes:
      - ./secrets/certs/fleet/fleet.crt:/usr/share/elastic-agent/cert.crt:ro
      - ./secrets/certs/fleet/fleet.key:/usr/share/elastic-agent/cert.key:ro
      - ./secrets/certs/kibana/elasticsearch-ca.pem:/usr/share/elastic-agent/ca.pem:ro      