version: '2.2'

services:
  keystore:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VER}
    command: bash /setup/setup-keystore.sh
    user: "0"
    volumes:
      - ./secrets:/secrets
      - ./setup/:/setup/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

  certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VER}
    command: bash /setup/setup-certs.sh
    container_name: certs
    user: "0"
    volumes:
      - ./secrets:/secrets
      - ./setup/:/setup/
    healthcheck:
      test: ["CMD-SHELL", "[ -f /secrets/certs/kibana/elasticsearch-ca.pem ]"]
      interval: 1s
      timeout: 5s
      retries: 120

#  elasticsearch:
#    depends_on:
#      certs:
#        condition: service_healthy
#    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VER}
#    volumes:
#      - ./secrets/certs:/usr/share/elasticsearch/config/certs
#      #- ./esdata01:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    environment:
#      - node.name=elasticsearch
#      - discovery.type=single-node
#      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
#      - bootstrap.memory_lock=true
#      - xpack.security.enabled=true
#      - xpack.security.http.ssl.enabled=true
#      - xpack.security.http.ssl.key=certs/elasticsearch/elasticsearch.key
#      - xpack.security.http.ssl.certificate=certs/elasticsearch/elasticsearch.crt
#      - xpack.security.http.ssl.certificate_authorities=certs/elasticsearch/ca.crt
#      - xpack.security.http.ssl.verification_mode=certificate
#      - xpack.security.transport.ssl.enabled=true
#      - xpack.security.transport.ssl.key=certs/elasticsearch/elasticsearch.key
#      - xpack.security.transport.ssl.certificate=certs/elasticsearch/elasticsearch.crt
#      - xpack.security.transport.ssl.certificate_authorities=certs/elasticsearch/ca.crt
#      - xpack.security.transport.ssl.verification_mode=certificate
#      - xpack.license.self_generated.type=${LICENSE}

     
  
