version: '3.5'
services:
  fleet_server:
    image: docker.elastic.co/beats/elastic-agent:8.0.0
    hostname: "scruffy_fleet"
    container_name: fleet
#    restart: always
    user: root
    environment:
      - "FLEET_SERVER_ENABLE=true"
#      - "FLEET_ENROLL=1"
#      - "FLEET_SERVER_INSECURE_HTTP=0"
#      - "FLEET_INSECURE=1"
#      - "FLEET-SERVER-POLICY=Fleet-Server"
      -  "FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDUyMDMyMDkyNDA6V2l5dXdHYkxTd0dLcGE5T2d0ejdFdw"
#      - "FLEET_ENROLLMENT_TOKEN=SG5wRERYOEIxNTRCTG9FU1I2Y0k6LXktMjZhc1BTUnluR0tQMjZNSkZGdw=="
      - "FLEET_SERVER_CERT=/usr/share/elastic-agent/cert.crt"
      - "FLEET_SERVER_CERT_KEY=/usr/share/elastic-agent/cert.key"
      - "FLEET_URL=https://10.0.0.198:8220"
      - "FLEET_SERVER_ELASTICSEARCH_HOST=https://10.0.0.198:9200"
      - "FLEET_SERVER_ELASTICSEARCH_CA=/usr/share/elastic-agent/ca.pem"
      - "KIBANA_FLEET_CA=/usr/share/elastic-agent/ca.pem"
      - "FLEET_CA=/usr/share/elastic-agent/ca.pem"
      - "ELASTICSEARCH_CA=/usr/share/elastic-agent/ca.pem"
      - "KIBANA_CA=/usr/share/elastic-agent/ca.pem"
      - "KIBANA_FLEET_SETUP:true"
      - "KIBANA_FLEET_HOST:https://10.0.0.198:5601"
      #- "KIBANA_FLEET_USERNAME:elastic"
      #- "KIBANA_FLEET_PASSWORD:password"
    ports:
      - "8220:8220"
    healthcheck:
      test: "curl -f http://127.0.0.1:8220/api/status | grep HEALTHY 2>&1 >/dev/null"
      retries: 12
      interval: 5s
    volumes:
      - ./secrets/certs/fleet/fleet.crt:/usr/share/elastic-agent/cert.crt:ro
      - ./secrets/certs/fleet/fleet.key:/usr/share/elastic-agent/cert.key:ro
      - ./secrets/certs/kibana/elasticsearch-ca.pem:/usr/share/elastic-agent/ca.pem:ro
