version: '3.5'
services:
  fleet_server:
    image: docker.elastic.co/beats/elastic-agent:8.0.0
    hostname: "scruffy_fleet"
    environment:
      - "FLEET_SERVER_ENABLE=1"
      - "FLEET_SERVER_INSECURE_HTTP=0"
      - "FLEET_INSECURE=1"
      - "AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NDUxOTUxMDM3NDQ6OWh4SEk3VE9SY0tKY0hJZkFDU2lNdw"
#      - "FLEET-SERVER-POLICY=2016d7cc-135e-5583-9758-3ba01f5a06e5"
      - "FLEET_SERVER_CERT=/usr/share/elastic-agent/cert.crt"
      - "FLEET_SERVER_CERT_KEY=/usr/share/elastic-agent/cert.key"
      - "FLEET_URL=https://10.0.0.198:8220"
      - "FLEET_SERVER_ELASTICSEARCH_HOST=https://10.0.0.198:9200"
      - "FLEET_SERVER_ELASTICSEARCH_CA=/usr/share/elastic-agent/ca.pem"
      - "KIBANA_FLEET_CA=/usr/share/elastic-agent/ca.pem"
      - "FLEET_CA=/usr/share/elastic-agent/ca.pem"
      - "ELASTICSEARCH_CA=/usr/share/elastic-agent/ca.pem"
      - "KIBANA_CA=/usr/share/elastic-agent/ca.pem"
    ports:
      - "8220:8220"
    healthcheck:
      test: "curl -f http://127.0.0.1:8220/api/status | grep HEALTHY 2>&1 >/dev/null"
      retries: 12
      interval: 5s
    volumes:
      - ./secrets/cert/fleet/fleet.crt:/usr/share/elastic-agent/cert.crt:ro
      - ./secrets/cert/fleet/fleet.key:/usr/share/elastic-agent/cert.key:ro
      - ./secrets/cert/kibana/elasticsearch-ca.pem:/usr/share/elastic-agent/ca.pem:ro
